import { MapDef } from "./gamemap/useMapGen";

export const demoMap: MapDef = {
    map: [
        "annnnnnn#nnnnnnnnnb",
        "w######.###.#####.#",
        "w#....#__#......#.e",
        "w#.....__########.#",
        "w#....#__.........#",
        "w######__########.#",
        "w......__#......#.#",
        "w######__#....#.#.#",
        "w#....#__#....#.#.#",
        "w#....#__#####..#.#",
        "w##.###__......##.#",
        "w.....#__#######..e",
        "c#sssss__#ssssssssd",
        "w######SS##########",
    ],
    empty: '#',
    legend: {
        '.': {
            north: 'bricks-big',
            south: 'bricks-big',
            east: 'bricks-big',
            west: 'bricks-big',
            up: 'stones-flat',
            down: 'dirt',
        },
        'n': {
            north: 'stones-gray',
            south: 'bricks-big',
            east: 'bricks-big',
            west: 'bricks-big',
            up: 'stones-flat',
            down: 'dirt',
        },
        'e': {
            north: 'bricks-big',
            south: 'bricks-big',
            east: 'stones-gray',
            west: 'bricks-big',
            up: 'stones-flat',
            down: 'dirt',
        },
        's': {
            north: 'bricks-big',
            south: 'stones-gray',
            east: 'bricks-big',
            west: 'bricks-big',
            up: 'stones-flat',
            down: 'dirt',
        },
        'S': {
            north: 'bricks-big',
            south: 'wood-door',
            east: 'stones-gray',
            west: 'stones-gray',
            up: 'stones-flat',
            down: 'bricks-castle',
        },
        'w': {
            north: 'bricks-big',
            south: 'bricks-big',
            east: 'bricks-big',
            west: 'stones-gray',
            up: 'stones-flat',
            down: 'dirt',
        },
        'a': {
            north: 'stones-gray',
            south: 'bricks-big',
            east: 'bricks-big',
            west: 'stones-gray',
            up: 'stones-flat',
            down: 'dirt',
        },
        'b': {
            north: 'stones-gray',
            south: 'bricks-big',
            east: 'stones-gray',
            west: 'bricks-big',
            up: 'stones-flat',
            down: 'dirt',
        },
        'c': {
            north: 'bricks-big',
            south: 'stones-gray',
            east: 'bricks-big',
            west: 'stones-gray',
            up: 'stones-flat',
            down: 'dirt',
        },
        'd': {
            north: 'bricks-big',
            south: 'stones-gray',
            east: 'stones-gray',
            west: 'bricks-big',
            up: 'stones-flat',
            down: 'dirt',
        },
        '_': {
            north: 'bricks-big',
            south: 'bricks-big',
            east: 'bricks-big',
            west: 'bricks-big',
            up: 'stones-flat',
            down: 'bricks-castle',
        },
    }
};
